### ISSUE TITLE
lr-mame2003 tate mode not working

### ISSUE THREAD

**Issue by strayel** [xovox/RetroCRT#41]
Enabling tate mode in retroarch to rotate vertical games results in the rotated content being scaled in the same viewport as displayed with screen horizontal.

**Comment by xovox** [comment]
can you attach a picture of what you're seeing?  if you're saying that on a horizontally oriented monitor the vertical games are scaled down and have bilinear filtering applied, that's intentional

if you're using a vertical screen and want vertical games displayed properly, run the RetroCRT configuration utility and select which way is up

**Comment by strayel** [comment]
I set retroarch.cfg allow_rotate to false and games now run fullscreen in vertical. Without that, enabling Tate mode in mame core rotated the game but scaled it to fit a horizontal screen.

**Comment by xovox** [comment]
that's by design.  if you want full screen vertical games you have to run the RetroCRT script from the RetroPie screen in ES and specify which way is up.  

I don't plan on making a physical screen i can twist around on a whim, and most people prefer the default mode i use than what you're looking for
